# Generated by Django 4.0.1 on 2022-02-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('phoneNumber', models.IntegerField(blank=True, null=True)),
                ('emailId', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.IntegerField(blank=True, null=True)),
                ('option2', models.IntegerField(blank=True, null=True)),
                ('option3', models.IntegerField(blank=True, null=True)),
                ('option4', models.IntegerField(blank=True, null=True)),
                ('voter', models.ManyToManyField(to='api.profile')),
            ],
        ),
    ]
