# Generated by Django 4.0.1 on 2022-03-09 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_poll_title_poll_title1_poll_title2_poll_title3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='title',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='title3',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='title4',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='voter',
        ),
        migrations.AddField(
            model_name='poll',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.voteoption'),
        ),
    ]
