# Generated by Django 4.0.1 on 2022-03-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_voteoption_remove_poll_option1_remove_poll_option2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='option',
        ),
        migrations.AddField(
            model_name='poll',
            name='option',
            field=models.ManyToManyField(blank=True, null=True, to='api.VoteOption'),
        ),
    ]
