# Generated by Django 4.0.1 on 2022-03-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_poll_option_poll_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteoption',
            name='votedUser',
            field=models.ManyToManyField(blank=True, null=True, to='api.Profile'),
        ),
    ]
