# Generated by Django 4.0.1 on 2022-03-09 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_voteoption_voteduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='option',
        ),
        migrations.AddField(
            model_name='poll',
            name='users',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
            preserve_default=False,
        ),
    ]
