# Generated by Django 4.0.1 on 2022-03-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_poll_option_poll_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='users',
        ),
        migrations.AddField(
            model_name='poll',
            name='option',
            field=models.ManyToManyField(blank=True, null=True, to='api.VoteOption'),
        ),
    ]
