# Generated by Django 4.0.1 on 2022-03-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_poll_users_poll_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voteoption',
            old_name='vote',
            new_name='voteValue',
        ),
    ]
