# Generated by Django 4.0.1 on 2022-03-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_vote_voteoption_votevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteoption',
            name='voteQuestion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
