# Generated by Django 4.0.1 on 2022-03-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_voteoption_votequestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voteoption',
            old_name='voteQuestion',
            new_name='voteStatement',
        ),
        migrations.AddField(
            model_name='poll',
            name='question',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
