# Generated by Django 4.0.1 on 2022-03-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_votequestion_voteoption_votestatement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='question',
        ),
        migrations.AddField(
            model_name='poll',
            name='pollQuestion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
